### ISSUE TITLE
port open

### ISSUE THREAD

**Issue by mcsim415** [sakaki-/gentoo-on-rpi-64bit#121] opened 2019-12-01 08:54 UTC
How to open port 19132?

**Comment by sakaki-** [comment] 2019-12-01 22:36
Hello @mcsim415,

sorry, I don't quite understand what you are asking here? The image, as shipped, does not actively firewall inbound connections (although this can of course be turned on easily enough).

Is there a particular service, using this port, that you'd like to enable?

Best, sakaki

**Comment by mcsim415** [comment] 2019-12-01 23:24
I couldn't find service command.
How can i do?
![Screenshot_20191202-082325](https://user-images.githubusercontent.com/48672862/69922151-12905c00-14dd-11ea-9364-de8c9c541247.png)

**Comment by sakaki-** [comment] 2019-12-02 00:29
Try `rc-service iptables save`?

**Comment by mcsim415** [comment] 2019-12-02 06:09
Oh. It's working.
![Screenshot_2019-12-02-15-09-16](https://user-images.githubusercontent.com/48672862/69934601-c3b2e880-1515-11ea-879e-f132f5c2b96b.png)

**Comment by mcsim415** [comment] 2019-12-02 06:25
Um.. It isn't working..
![Screenshot_2019-12-02-15-24-51](https://user-images.githubusercontent.com/48672862/69935353-f1009600-1517-11ea-90c1-e1f53c6c6f0a.png)
![Screenshot_2019-12-02-15-25-02](https://user-images.githubusercontent.com/48672862/69935356-f52cb380-1517-11ea-8654-715a38e34a27.png)

**Comment by mcsim415** [comment] 2019-12-02 06:26
22 port is open.
But 19132 port is close..

**Comment by mcsim415** [comment] 2019-12-02 06:27
In fact, I can't use Linux well..

**Comment by sakaki-** [comment] 2019-12-02 07:34
You need a service listening on this port also. Try running `netstat -vatn` and `netstat -vaun` to see which TCP and UDP services are running, on which ports.

**Comment by mcsim415** [comment] 2019-12-02 10:09
![Screenshot_2019-12-02-19-09-01](https://user-images.githubusercontent.com/48672862/69950721-384a4f00-1537-11ea-9028-43c93c300e2f.png)

**Comment by mcsim415** [comment] 2019-12-02 10:16
I want open my minecraft pe server!

**Comment by mcsim415** [comment] 2019-12-02 11:44
Ummm

**Comment by sakaki-** [comment] 2019-12-02 14:27
OK, from your `netstat` output, you have a UDP service listening on port 19132, presumably [pocket minecraft protocol](https://wiki.vg/Pocket_Minecraft_Protocol).

As such, you need to allow _inbound_ connections on that port for UDP (rather than outbound connections for TCP, which is what you did above).

Try:

```console
# iptables -P OUTPUT ACCEPT
# iptables -I INPUT 1 -p udp --dport 19132 -j ACCEPT
```
verify your ruleset with
```console
# iptables-save
```

hth, sakaki

**Comment by mcsim415** [comment] 2019-12-03 07:14
Ummm.?
![Screenshot_2019-12-03-16-13-54](https://user-images.githubusercontent.com/48672862/70028425-f3322580-15e7-11ea-9a58-028c6a2338f0.png)

**Comment by sakaki-** [comment] 2019-12-03 07:31
OK, so as I suspected, the port _is_ open (you have in fact many rules ^-^ inserted to do that, and also, the *default* stance for `INPUT` is `ACCEPT` too; so nothing on this local firewall is in fact blocking you &mdash; which is as I would have expected, unless you had explicitly set up something to the contrary).

You also (per your `netstat -vaun` output [earlier](https://github.com/sakaki-/gentoo-on-rpi-64bit/issues/121#issuecomment-560326539)) have a service listening on this port, on all interfaces.

So you should be able to connect to this service OK. Check the IP address of your RPi using `ifconfig`, and then try to connect from another system on your local network first. Once that works, you can ensure port forwarding etc. on your external router is working.

**Comment by mcsim415** [comment] 2019-12-03 07:41
no... Port isn't open..
[Go here and leamo.kro.kr;19132](https://www.yougetsignal.com/tools/open-ports/)

**Comment by mcsim415** [comment] 2019-12-03 07:43
I'll check it port state soon.

**Comment by mcsim415** [comment] 2019-12-03 09:53
Haaa
![Screenshot_2019-12-03-18-51-58](https://user-images.githubusercontent.com/48672862/70039966-0e0f9480-15fe-11ea-973d-2a0f69c57f45.png)

**Comment by mcsim415** [comment] 2019-12-03 09:53
Oh my gosh...

**Comment by mcsim415** [comment] 2019-12-03 09:53
It is still close

**Comment by sakaki-** [comment] 2019-12-03 10:31
The issue is likely with your external router allowing / forwarding port 22, but not your target port. You need to fix that. The issue is not with the Pi.

Anyway, I am closing this issue and blocking you as a user, since [your post above](https://github.com/sakaki-/gentoo-on-rpi-64bit/issues/121#issuecomment-561089008) contains inappropriate sexual imagery.

I have reported this also to GitHub.

S.

**Closed by sakaki-** 2019-12-03 10:31 UTC
